version: 2

models:

  - name: stg_addresses
    description: Address for a user

    columns:
      - name: address_id
        description: unique id for an address assigned to a user.
        tests:
          - unique

  - name: stg_users
    description: This table is derived from users table in the source. It has details of users who order products with Greenery.

    columns:
      - name: user_id
        description: unique id of a user.
        tests: 
          - unique
          - not_null
          - relationships:
              to: ref('stg_users')
              field: user_id

      - name: first_name
        description: First name of the user.

      - name: last_name
        description: Last name of the user.

      - name: email
        description: email of the user

      - name: phone_number
        description: phone number of the user.

      - name: created_at
        description: Date and time when user was created.

      - name: address_id
        description: Address_id of the address defined for the users, stored in stg_addresses table.

  - name: stg_promos
    description: Table to store promos for sales at Greenery

    columns:
      - name: promo_id
        description: Unique id for promos.
        tests:
          - unique
          - not_null

  - name: stg_products
    description: Table for products sold by greenery.
    
    columns:
      - name: product_id
        description: unique id of a product
        test:
          - unique
          - not_null


  - name: stg_orders
    description: Table for storing details of orders created.

    columns:
      - name: order_id
        description: unique id of a Orders
        test:
          - unique
          - not_null

      - name: user_id
        description: id of user making the order, references stg_users
        test:
          - relationships:
              to: ref('stg_users')
              field: user_id

      - name: address_id
        description: address for the order, references stg_addresses
        test:
          - relationships:
              to: ref('stg_addresses')
              field: address_id

      - name: created_at
        description: date and time of when the order was created.

      - name: status
        description: status of the order. shipped, preparing or delivered.

  - name: stg_order_items
    description: products part of an order & their quantities.

    columns:
      - name: order_id
        description: order reference
        test:
          - not_null
          - relationships:
              to: ref('stg_orders')
              field: order_id


      - name: product_id
        description: product_id of the product which is part of the order
        test:
          - not_null
          - relationships:
              to: ref('stg_products')
              field: product_id

      - name: quantity
        description: number of products being ordered

  - name: stg_events
    description: Log of user activity on greenery.com

    columns:
      - name: event_id
        description: unique id for an event
        tests:
          - not_null
          - unique
      - name: session_id
        description: session_id of the user activity. There could be multiple events for a session.

      - name: event_type
        description: type of the user activity, possible values are add_to_cart, checkout, page_view, package_shipped

      - name: order_id
        description: order reference
        test:
          - relationships:
              to: ref('stg_orders')
              field: order_id


      - name: product_id
        description: product_id of the product which is part of the order
        test:
          - relationships:
              to: ref('stg_products')
              field: product_id

      - name: user_id
        description: id of user making the order, references stg_users
        test:
          - relationships:
              to: ref('stg_users')
              field: user_id


      
