version: 2

models:

  - name: stg_addresses
    description: Address for a user

    columns:
      - name: address_id
        description: unique id for an address assigned to a user.
        tests:
          - unique

  - name: stg_users
    description: This table is derived from users table in the source. It has details of users who order products with Greenery.

    columns:
      - name: user_id
        description: unique id of a user.
        tests: 
          - unique
          - not_null

      - name: first_name
        description: First name of the user.

      - name: last_name
        description: Last name of the user.

      - name: email
        description: email of the user

      - name: phone_number
        description: phone number of the user.

      - name: created_at
        description: Date and time when user was created.

      - name: address_id
        description: Address_id of the address defined for the users, stored in stg_addresses table.

  - name: stg_promos
    description: Table to store promos for sales at Greenery

    columns:
      - name: promo_id
        description: Unique id for promos.
        tests:
          - unique
          - not_null

  - name: stg_products
    description: Table for products sold by greenery.
    
    columns:
      - name: product_id
        description: unique id of a product
        test:
          - unique
          - not_null


  - name: stg_orders
    description: Table for storing details of orders created.

    columns:
      - name: order_id
        description: unique id of a Orders
        test:
          - unique
          - not_null

    columns:
      - name: user_id
        description: id of user making the order, references stg_users

    columns:
      - name: address_id
        description: address for the order, references stg_addresses

    columns:
      - name: created_at
        description: date and time of when the order was created.

    columns:
      - name: status
        description: status of the order. shipped, preparing or delivered.



      
